# Generated by Django 3.1.1 on 2020-09-17 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracks', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Trakc',
            new_name='Track',
        ),
    ]
